main toast new design
Elao/ElaoConsentBundle pull request #1
Opened 2021-09-16 11:51 UTC by sludovicdelys

The design of the main toaster for the cookies 🍪 has been modified

2021-09-16 14:13 UTC, cmozzati commented on public/css/style.css
> +  width: 420px;
T'es passée sur 420 finalement ? Une raison particulière ?

2021-09-17 08:42 UTC, sludovicdelys commented on public/css/style.css
> +  width: 420px;
ça faisait beaucoup plus petit sur mon écran, à mon souvenir. Tu veux que je ré-essaye avec une `width: 320px` sur la classe `.elao-consent` ?

2021-09-17 09:02 UTC, cmozzati commented on public/css/style.css
> +  width: 420px;
faudrait qu'on puisse voir "en vrai" pour que je te réponde ^^

2021-09-17 09:10 UTC, sludovicdelys commented on public/css/style.css
> +  width: 420px;
`width: 420px`

![Capture d’écran 2021-09-17 à 11 09 00](https://user-images.githubusercontent.com/74900669/133756892-37cecf6b-3312-46f4-b9be-f4668cc17b7c.png)

et `width: 320px`

![Capture d’écran 2021-09-17 à 11 09 15](https://user-images.githubusercontent.com/74900669/133757008-d04bb5ac-3610-4e20-8b07-393a09e81476.png)

2021-09-17 09:12 UTC, sludovicdelys commented on public/css/style.css
> +  width: 420px;
L'écran est à 1050px sur les deux exemples

2021-09-17 09:39 UTC, cmozzati commented on public/css/style.css
> +  width: 420px;
ok pour le 420, par contre dans les boutons c'est pas la bonne typo :)

2021-09-21 08:52 UTC, ameliedefrance requested changes

2021-09-21 08:52 UTC, ameliedefrance commented on translations/elao_consent.fr.yaml
> +        consent_message: Des cookies, petits fichiers informatiques, peuvent être déposés sur votre terminal. Si vous y consentez, le responsable du site pourra recueillir des statistiques de visites
Il reste une balise `<a>` fermante à la fin de cette ligne

2021-09-21 08:52 UTC, ameliedefrance commented on translations/elao_consent.fr.yaml
> +        save: Enregistrer
Il manque une ligne vide à la fin de ce fichier

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  font-size: 16px;
Cette `font-size` est répétée sur les boutons `reject-all` et `accept-all` -> il faut la mettre dans `elao-consent__actions button` pour ne pas la répéter

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  margin: 15px 0 0;
```suggestion
  margin: 20px 0 0;
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  border-top: 1px solid #F1F1F1;
Pas de couleurs en dur

```suggestion
  border-top: 1px solid var(--default-elao-consent-secondary);
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  border-radius: 0;
Pourquoi supprimer le border-radius dans ce bouton ? Le border-radius du toast est passé à 4px donc ici on devrait avoir 

```suggestion
  border-radius: 0 0 4px 0;
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  border-radius: 0 0 0 15px;
Ici le border-radius devrait suivre celui du toast. 

```suggestion
  border-radius: 0 0 0 4px;
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  border-radius: 0 0 15px 15px;
Même border-radius que sur le toast 
```suggestion
  border-radius: 0 0 4px 4px;
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +
Supprimer cette ligne vide

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +
Idem ici, ligne vide

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
> +  padding: 20px 40px 0;
Tu as passé le padding de `.message` à `0 20px`. Il faut réaligner le contenu du summary aussi.

```suggestion
  padding: 20px 20px 0;
```

2021-09-21 08:52 UTC, ameliedefrance commented on public/css/style.css
>  /* Radio button  */
```suggestion
/* Radio button  */

.radio-button {
  display: flex;
}
```

2021-09-21 08:55 UTC, ameliedefrance requested changes

2021-09-21 08:55 UTC, ameliedefrance commented on public/css/style.css
> +  font-size: 16px;
```suggestion
  font-size: 15px;
```

2021-09-21 08:55 UTC, ameliedefrance commented on public/css/style.css
> +  font-size: 16px;
Et on va plutôt la passer à 15px, ça nous fait gagner un peu d'espace

2021-09-21 12:54 UTC, ameliedefrance requested changes

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +
On va uniformiser les border-radius pour ne pas avoir à les changer partout à la fois. Parfois on a 4px, parfois 5px. On va mettre 4px partout.

Ici tu peux créer une variable css `--default-elao-consent-border-radius: var(--elao-consent-border-radius, 4px);` et aller remplacer tous les `4px` et `5px` de border-radius par `var(--default-elao-consent-border-radius)`.

Exemple : 
```
border-radius: 0 0 var(--default-elao-consent-border-radius) 0;
```

Désormais si on veut changer le border-radius on ira modifier uniquement dans les variables.

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  width: 420px;
La largeur du bloc est un peu grande. On va tout réduire ici. 
```suggestion
  width: 350px;
  font-size: 14px;
```

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  right: -10px;
Pour décaler l'icône il faut jouer sur le padding du parent plutôt que sur le `right` du `:before`. Le but c'est que l'icône vienne se caler dans le padding du parent sans en déborder.

```
.elao-consent__details summary {
  padding-right: 35px;
}

.elao-consent__details summary:before {
  right: 0;
  font-size: 27px;
}
```

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  right: -10px;
Avant 

<img width="219" alt="Capture d’écran 2021-09-21 à 14 36 05" src="https://user-images.githubusercontent.com/25897625/134171535-5bc77a05-84e7-4441-a825-2bc80869d595.png">

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  right: -10px;
Après 

<img width="226" alt="Capture d’écran 2021-09-21 à 14 41 23" src="https://user-images.githubusercontent.com/25897625/134172228-c0511ff5-14d7-477e-b57d-4a3a191a039b.png">

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  right: -10px;
Maintenant l'icône est a une `font-size` différente de celle de "choisir mes cookies". Donc le cookie dépasse un peu en bas. Pour gommer ça on va aligner verticalement le cookie par rapport à "choisir mes cookies".

```
// l'icône est déjà en position absolute, on va se servir de ça pour centrer
.elao-consent__details summary {
  position: relative;
}

.elao-consent__details summary:before {
  top: 50%;
  transform: translateY(-50%);
}
```

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  font-size: 16px;
On passe tout en 14px, donc ici aussi 14px.

2021-09-21 12:54 UTC, ameliedefrance commented on public/css/style.css
> +  border-top: 1px solid var(--default-elao-consent-secondary);
Ce `border-top` est présent sur tous les boutons dans `.elao-consent__actions`. Si tu regardes bien on apperçoit une ligne de 1px très claire même sur le bouton bleu foncé. C'est pas ce qu'on veut.

On va laisser le border présent sur tous les boutons dans `.elao-consent__actions`, en revanche on va le mettre en couleur claire uniquement sur le bouton `reject-all`.

```
.elao-consent__actions button {
  border-top: 1px solid var(--default-elao-consent-primary);
}

.elao-consent__actions button.reject-all {
  border-top-color: var(--default-elao-consent-secondary);
}
```

2021-09-21 12:55 UTC, ameliedefrance requested changes

2021-09-21 12:55 UTC, ameliedefrance commented on public/css/style.css
> +  height: 50px;
Comme on a tout réduit on va réduire la hauteur des boutons aussi.

```suggestion
  height: 40px;
```

2021-09-21 12:56 UTC, ameliedefrance requested changes

2021-09-21 13:15 UTC, ameliedefrance requested changes

2021-09-21 13:15 UTC, ameliedefrance commented on public/css/style.css
>  .radio-button label {
Pour ne pas créer d'effets de bord indésirables sur les sites où on pose le cookie consent, on va bien englober tous nos styles dans la classe `.elao-consent`. Donc tu peux l'ajouter devant tout ce qui est `.radio-button` ici.

2021-09-22 07:30 UTC, ameliedefrance requested changes

2021-09-22 07:30 UTC, ameliedefrance commented on public/css/style.css
> +  --default-elao-consent-border-radius: var(--elao-consent-border-radius);
```suggestion
  --default-elao-consent-border-radius: var(--elao-consent-border-radius, 4px);
```

2021-09-22 07:30 UTC, ameliedefrance commented on public/css/style.css
> +  right: 0px;
Pas d'unité sur le 0 ici

2021-09-22 07:30 UTC, ameliedefrance commented on public/css/style.css
> +  font-size: 30px;
```suggestion
  font-size: 27px;
```

2021-09-22 07:30 UTC, ameliedefrance commented on public/css/style.css
>  @media (max-width: 650px) {
On a deux media queries dans `style.css`, tu peux prendre tout ce qu'il y a dans ce `@media (max-width: 650px)` et le déplacer au début du même media query tout en bas ⬇️

2021-09-22 07:36 UTC, ameliedefrance commented
Autre détail : dans `toast.html.twig` : 
```suggestion
{% else %}
        <p class="message">{{ 'elao_consent.messages.consent_message'|trans({}, 'elao_consent')|raw }}</p>
        <div class="elao-consent__actions"></div>
{% endif %}
```

2021-09-22 12:08 UTC, ameliedefrance approved these changes
👏👏

2021-09-23 07:53 UTC, cmozzati approved these changes
👏

2021-09-23 08:51 UTC, maximecolin approved these changes

2023-02-21 14:57 UTC, sludovicdelys commented
Plop @maximecolin @ameliedefrance je peux merge et fermer cette PR ? :D

2023-02-21 16:50 UTC, cmozzati commented
2 ans plus tard, bravo 🤣

2023-02-22 08:56 UTC, ameliedefrance commented
🙈🙈🙈

2023-02-22 09:00 UTC, merged